Add rootKeyPath in GarageRequestParameterContainer
slightair/GarageClientSwift pull request #3
Opened 2016-12-14 04:04 UTC by hatuyuki4

Add rootKeyPath in GarageRequestParameterContainer.
It is used for decoding by Himotoki.

2016-12-20 08:22 UTC, slightair requested changes
Thanks! 🍶

2016-12-20 08:22 UTC, slightair commented on Sources/GarageRequestType.swift
> +    var rootKeyPath: [String]? { get }
The `rootKayPath` is option parameter for decode process.
So I propose followings.

- introduce `GarageDecodeResponseParameterContainer` and add default implementation.
- change name `rootKeyPath` => `decodeRootKeyPath`
- change variable type of `rootKeyPath` to `KeyPath` (Himotoki)

2016-12-20 08:22 UTC, slightair commented on Sources/RequestBuilder.swift
> +            guard let resource: [D] = try! decodeArray(object, rootKeyPath: KeyPath(rootKeyPath)) as [D]? else {
It is not necessary to use `try!`.
Maybe, I had been used `try!` in old `swift3` branch and already fixed.

2017-01-09 13:42 UTC, hatuyuki4 commented on Sources/GarageRequestType.swift
> +    var rootKeyPath: [String]? { get }
Rename to `decodeRootKeyPath` and change variable type.

https://github.com/slightair/GarageClientSwift/pull/3/files#diff-29b941133987425a8183ef2f69e3273cR8

2017-01-09 13:42 UTC, hatuyuki4 commented on Sources/RequestBuilder.swift
> +            guard let resource: [D] = try! decodeArray(object, rootKeyPath: KeyPath(rootKeyPath)) as [D]? else {
Fix it.
https://github.com/slightair/GarageClientSwift/pull/3/files#diff-1d696d720be823d13aae2986bcc884f5R125

2017-01-09 13:45 UTC, hatuyuki4 commented
@slightair 
Thank you for reviewing. Fixed any points.

2017-01-10 09:56 UTC, slightair commented
OK, Thanks!

2017-01-10 09:56 UTC, merged